apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.frontend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    service: frontend
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        {{- with .Values.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        service: frontend
    spec:
      containers:
        - image: {{ .Values.images.frontend }}
          name: frontend
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: frontend
status:
  loadBalancer: {}
