apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.hammerdebug.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    service: hammerdebug
  name: hammerdebug
spec:
  replicas: {{ .Values.hammerdebug.replicas }}
  selector:
    matchLabels:
      service: hammerdebug
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        {{- with .Values.hammerdebug.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        service: hammerdebug
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z -w4 hammermanager 8001; do echo waiting for dependencies; sleep 1; done;']
      containers:
        - env:
            - name: IS_DEBUG
              value: "true"
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.hammer }}
          imagePullPolicy: IfNotPresent
          name: hammerdebug
          resources: {}
      restartPolicy: Always
