apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: []
    scrape_configs:
      - job_name: "backend"
        metrics_path: '/metrics/scrape'
        static_configs:
          - targets: ["alaz-backend:8008"]
        basic_auth:
          username: alaz-backend
          password: jRTyHAbUHYE37hRBgEz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.prometheus.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      annotations:
        {{- with .Values.prometheus.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.images.prometheus }}
          args:
            - "--config.file=/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--storage.tsdb.retention=10d"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          emptyDir: {}
---
{{- if ne (int .Values.prometheus.replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus
{{- end -}}
