apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.rabbitmq.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      service: rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        {{- with .Values.rabbitmq.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        service: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq }}
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
---
{{- if ne (int .Values.rabbitmq.replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq
status:
  loadBalancer: {}
{{- end -}}
