apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.redisBackend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    service: redis-backend
  name: redis-backend
spec:
  replicas: {{ .Values.redisBackend.replicas }}
  selector:
    matchLabels:
      service: redis-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        {{- with .Values.redisBackend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        service: redis-backend
    spec:
      containers:
        - name: redis-backend
          image: {{ .Values.images.redis }}
          resources: {}
      restartPolicy: Always
status: {}
---
{{- if ne (int .Values.redisBackend.replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-backend
  name: redis-backend
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis-backend
status:
  loadBalancer: {}
---
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.redisAlazBackend.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    service: redis-alaz-backend
  name: redis-alaz-backend
spec:
  replicas: {{ .Values.redisAlazBackend.replicas }}
  selector:
    matchLabels:
      service: redis-alaz-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        {{- with .Values.redisAlazBackend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        service: redis-alaz-backend
    spec:
      containers:
        - name: redis-alaz-backend
          image: {{ .Values.images.redis }}
          resources: {}
      restartPolicy: Always
status: {}
---
{{- if ne (int .Values.redisAlazBackend.replicas) 0 -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-alaz-backend
  name: redis-alaz-backend
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis-alaz-backend
status:
  loadBalancer: {}
{{- end -}}
